// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/statistics/statistics.proto

package statistics

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserOrdersStatisticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserOrdersStatisticsRequest) Reset() {
	*x = UserOrdersStatisticsRequest{}
	mi := &file_proto_statistics_statistics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserOrdersStatisticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOrdersStatisticsRequest) ProtoMessage() {}

func (x *UserOrdersStatisticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_statistics_statistics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOrdersStatisticsRequest.ProtoReflect.Descriptor instead.
func (*UserOrdersStatisticsRequest) Descriptor() ([]byte, []int) {
	return file_proto_statistics_statistics_proto_rawDescGZIP(), []int{0}
}

func (x *UserOrdersStatisticsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserOrdersStatisticsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TotalOrders       int32                  `protobuf:"varint,1,opt,name=total_orders,json=totalOrders,proto3" json:"total_orders,omitempty"`
	OrdersByHour      map[string]int32       `protobuf:"bytes,2,rep,name=orders_by_hour,json=ordersByHour,proto3" json:"orders_by_hour,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // Key is hour (0-23), value is order count
	AverageOrderValue float64                `protobuf:"fixed64,3,opt,name=average_order_value,json=averageOrderValue,proto3" json:"average_order_value,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UserOrdersStatisticsResponse) Reset() {
	*x = UserOrdersStatisticsResponse{}
	mi := &file_proto_statistics_statistics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserOrdersStatisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOrdersStatisticsResponse) ProtoMessage() {}

func (x *UserOrdersStatisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_statistics_statistics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOrdersStatisticsResponse.ProtoReflect.Descriptor instead.
func (*UserOrdersStatisticsResponse) Descriptor() ([]byte, []int) {
	return file_proto_statistics_statistics_proto_rawDescGZIP(), []int{1}
}

func (x *UserOrdersStatisticsResponse) GetTotalOrders() int32 {
	if x != nil {
		return x.TotalOrders
	}
	return 0
}

func (x *UserOrdersStatisticsResponse) GetOrdersByHour() map[string]int32 {
	if x != nil {
		return x.OrdersByHour
	}
	return nil
}

func (x *UserOrdersStatisticsResponse) GetAverageOrderValue() float64 {
	if x != nil {
		return x.AverageOrderValue
	}
	return 0
}

type UserStatisticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserStatisticsRequest) Reset() {
	*x = UserStatisticsRequest{}
	mi := &file_proto_statistics_statistics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserStatisticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStatisticsRequest) ProtoMessage() {}

func (x *UserStatisticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_statistics_statistics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStatisticsRequest.ProtoReflect.Descriptor instead.
func (*UserStatisticsRequest) Descriptor() ([]byte, []int) {
	return file_proto_statistics_statistics_proto_rawDescGZIP(), []int{2}
}

type UserStatisticsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalUsers    int32                  `protobuf:"varint,1,opt,name=total_users,json=totalUsers,proto3" json:"total_users,omitempty"`
	Users         []*UserOrderCount      `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserStatisticsResponse) Reset() {
	*x = UserStatisticsResponse{}
	mi := &file_proto_statistics_statistics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserStatisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStatisticsResponse) ProtoMessage() {}

func (x *UserStatisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_statistics_statistics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStatisticsResponse.ProtoReflect.Descriptor instead.
func (*UserStatisticsResponse) Descriptor() ([]byte, []int) {
	return file_proto_statistics_statistics_proto_rawDescGZIP(), []int{3}
}

func (x *UserStatisticsResponse) GetTotalUsers() int32 {
	if x != nil {
		return x.TotalUsers
	}
	return 0
}

func (x *UserStatisticsResponse) GetUsers() []*UserOrderCount {
	if x != nil {
		return x.Users
	}
	return nil
}

type UserOrderCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderCount    int32                  `protobuf:"varint,2,opt,name=order_count,json=orderCount,proto3" json:"order_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserOrderCount) Reset() {
	*x = UserOrderCount{}
	mi := &file_proto_statistics_statistics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserOrderCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOrderCount) ProtoMessage() {}

func (x *UserOrderCount) ProtoReflect() protoreflect.Message {
	mi := &file_proto_statistics_statistics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOrderCount.ProtoReflect.Descriptor instead.
func (*UserOrderCount) Descriptor() ([]byte, []int) {
	return file_proto_statistics_statistics_proto_rawDescGZIP(), []int{4}
}

func (x *UserOrderCount) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserOrderCount) GetOrderCount() int32 {
	if x != nil {
		return x.OrderCount
	}
	return 0
}

var File_proto_statistics_statistics_proto protoreflect.FileDescriptor

const file_proto_statistics_statistics_proto_rawDesc = "" +
	"\n" +
	"!proto/statistics/statistics.proto\x12\n" +
	"statistics\"6\n" +
	"\x1bUserOrdersStatisticsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x94\x02\n" +
	"\x1cUserOrdersStatisticsResponse\x12!\n" +
	"\ftotal_orders\x18\x01 \x01(\x05R\vtotalOrders\x12`\n" +
	"\x0eorders_by_hour\x18\x02 \x03(\v2:.statistics.UserOrdersStatisticsResponse.OrdersByHourEntryR\fordersByHour\x12.\n" +
	"\x13average_order_value\x18\x03 \x01(\x01R\x11averageOrderValue\x1a?\n" +
	"\x11OrdersByHourEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\x17\n" +
	"\x15UserStatisticsRequest\"k\n" +
	"\x16UserStatisticsResponse\x12\x1f\n" +
	"\vtotal_users\x18\x01 \x01(\x05R\n" +
	"totalUsers\x120\n" +
	"\x05users\x18\x02 \x03(\v2\x1a.statistics.UserOrderCountR\x05users\"J\n" +
	"\x0eUserOrderCount\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vorder_count\x18\x02 \x01(\x05R\n" +
	"orderCount2\xdd\x01\n" +
	"\x11StatisticsService\x12l\n" +
	"\x17GetUserOrdersStatistics\x12'.statistics.UserOrdersStatisticsRequest\x1a(.statistics.UserOrdersStatisticsResponse\x12Z\n" +
	"\x11GetUserStatistics\x12!.statistics.UserStatisticsRequest\x1a\".statistics.UserStatisticsResponseB\x1cZ\x1aecommerce/proto/statisticsb\x06proto3"

var (
	file_proto_statistics_statistics_proto_rawDescOnce sync.Once
	file_proto_statistics_statistics_proto_rawDescData []byte
)

func file_proto_statistics_statistics_proto_rawDescGZIP() []byte {
	file_proto_statistics_statistics_proto_rawDescOnce.Do(func() {
		file_proto_statistics_statistics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_statistics_statistics_proto_rawDesc), len(file_proto_statistics_statistics_proto_rawDesc)))
	})
	return file_proto_statistics_statistics_proto_rawDescData
}

var file_proto_statistics_statistics_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_statistics_statistics_proto_goTypes = []any{
	(*UserOrdersStatisticsRequest)(nil),  // 0: statistics.UserOrdersStatisticsRequest
	(*UserOrdersStatisticsResponse)(nil), // 1: statistics.UserOrdersStatisticsResponse
	(*UserStatisticsRequest)(nil),        // 2: statistics.UserStatisticsRequest
	(*UserStatisticsResponse)(nil),       // 3: statistics.UserStatisticsResponse
	(*UserOrderCount)(nil),               // 4: statistics.UserOrderCount
	nil,                                  // 5: statistics.UserOrdersStatisticsResponse.OrdersByHourEntry
}
var file_proto_statistics_statistics_proto_depIdxs = []int32{
	5, // 0: statistics.UserOrdersStatisticsResponse.orders_by_hour:type_name -> statistics.UserOrdersStatisticsResponse.OrdersByHourEntry
	4, // 1: statistics.UserStatisticsResponse.users:type_name -> statistics.UserOrderCount
	0, // 2: statistics.StatisticsService.GetUserOrdersStatistics:input_type -> statistics.UserOrdersStatisticsRequest
	2, // 3: statistics.StatisticsService.GetUserStatistics:input_type -> statistics.UserStatisticsRequest
	1, // 4: statistics.StatisticsService.GetUserOrdersStatistics:output_type -> statistics.UserOrdersStatisticsResponse
	3, // 5: statistics.StatisticsService.GetUserStatistics:output_type -> statistics.UserStatisticsResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_statistics_statistics_proto_init() }
func file_proto_statistics_statistics_proto_init() {
	if File_proto_statistics_statistics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_statistics_statistics_proto_rawDesc), len(file_proto_statistics_statistics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_statistics_statistics_proto_goTypes,
		DependencyIndexes: file_proto_statistics_statistics_proto_depIdxs,
		MessageInfos:      file_proto_statistics_statistics_proto_msgTypes,
	}.Build()
	File_proto_statistics_statistics_proto = out.File
	file_proto_statistics_statistics_proto_goTypes = nil
	file_proto_statistics_statistics_proto_depIdxs = nil
}
